AWSTemplateFormatVersion: 2010-09-09
Description: Serverless Aurora MySQL DB for NextFlow Tower

Parameters:

  LogGroupName:
    Description: Name of your log group.
    Type: String

  DaysToRetainLogs:
    Description: Number of days to keep logs before deletion.
    Type: Integer
    Default: 7

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: String
      RetentionInDays: 7
